apiVersion: v1
kind: Pod
metadata:
  name: high-cpu
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "4"        # 4 CPU core
          memory: "1Gi"   # 1 GB RAM
        limits:
          cpu: "4"        # 4 CPU cores
          memory: "1Gi"   # 1 GB RAM

