apiVersion: v1
kind: Pod
metadata:
  name: high-ram
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "1"        # 1 CPU core
          memory: "4Gi"   # 4 GB RAM
        limits:
          cpu: "1"        # 1 CPU cores
          memory: "4Gi"   # 4 GB RAM

