apiVersion: v1
kind: Pod
metadata:
  name: medium-ram
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "1"        # 1 CPU core
          memory: "2Gi"   # 2 GB RAM
        limits:
          cpu: "1"        # 1 CPU core
          memory: "2Gi"   # 2 GB RAM

